### PR TITLE
LeadingZero should remove 0s, not add them

### PR DESCRIPTION
**Pull request by than**

### CODE REVIEW

**Comment by HugoGiraudel** [comment]
Actually it depends on what you prefer. The README should display both anyway. :)

**Comment by than** [comment]
True! Just looked at what scss-lint recommended, but missed it supports both ways.

**Comment by than** [comment]
Updated the PR. This was a huge help for me today. Thanks for putting it together.

**Comment by HugoGiraudel** [comment]
Thanks!

**Pull request merged**
